### PR TITLE
I must not eval().

### PR DESCRIPTION
**Pull request by aetherknight**
Eval is the company-killer. Eval() is the little-death that brings total
company obliteration. I will face my eval()s. I will permit it to pass
over me and through me. And when it has gone past I will turn the inner
developer to see its path. Where the eval() has gone there will be
nothing. Only proper use of reflection APIs will remain.

### CODE REVIEW

**Comment by ajmurmann** [comment]
:+1: 

I like your comment better than the text in the style guide

**Comment by aetherknight** [comment]
Would you prefer the commit text as the text in the style guide? I'd also be happy with rephrasings of my actual text change, as long as it gets the point across.

**Comment by aetherknight** [comment]
@ajmurmann will rely on you to merge, if you prefer my PR. =]

**Comment by Spaceghost** [comment]
I rather like this. We had discussed going into depth about the situation or removing it, but we left it.

I think a good improvement, if you're looking for one, is to take a string of code evaluation in a project and include a sanitized version of whatever you choose and provide a 'good' version using ruby's excellent metaprogramming facilities in addition to making the 'bad' SoC.

Either way, :+1:!

**Pull request merged**
