### PR TITLE
Common sense FTW.

### PR DESCRIPTION
**Pull request by f1337**
We _really_ like the Source Code Layout section. Smart, common-sense, "how we do it" advice. All good.

The rest is really just linting rules, and could be encapsulated in a tool. Let's explore that idea?

### CODE REVIEW

**Comment by ajmurmann** [comment]
We are already planning on using rubocop for which the standard rules already exist. So we would just have to customize those.

**Comment by aetherknight** [comment]
I think we should probably make another stab at a gem/metagem/tool that either has dependencies on other gems that will install tools, or that provides scripts to install a lot of common tools that should be available in our development environment.

I am more thinking of something that can bootstrap/update our tools (Eg, the pivotal git scripts, something to update a home directory version of the .pairs file, maybe install linters, brakeman, etc. maybe a script to build a workspace that could then also be used in the developer vm), rather than a gem that would be included in each rails app.

**Comment by Spaceghost** [comment]
@aetherknight I'm actually setting up [kitchenplan](http://kitchenplan.github.io/kitchenplan/) right now. It's incredibly easy and comes down to using/adding chef libraries to your `Cheffile` and then configuring attributes and recipes to run when you execute `kitchenplan provision`.

Will share quite soon, though I don't personally know whether it's best to share a single repo, or get more clever. Here's the author's [config](https://github.com/roderik/kitchenplan-config), which is a stellar example.

**Comment by Spaceghost** [comment]
@f1337 While I don't mind how we achieve the goal of consistency and homogenous codebases, I think anyone who uses our style should be able to read our rules in the simplest representation possible for them to be able to get back to the important tasks, like breaking builds and tests!

**Comment by Spaceghost** [comment]
What's the status on this? Personally, I'd like to have all these agreements as something I can link to with the goal of affording someone a wider view of why a certain style is preferred over another and to open the discussion of a change of style to the team if the faux pas isn't one that someone (a pair) feels is part of our goal to have homogenous code style.

**Pull request closed without merging**
